[tool.poetry]
name = "common-lit-kaggle"
version = "0.1.0"
description = ""
authors = ["Paolo Rechia <paolorechia@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
black = "^23.7.0"
pylint = "^2.17.4"
mypy = "^1.4.1"
polars = "^0.18.8"
isort = "^5.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
